#!/bin/bash
apt update && apt install python3-pip -y
git clone https://github.com/Kushal-Gadige/image_classification.git
cd image_classification/
pip3 install -r requirements.txt --no-cache-dir
python3 app.py
